/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NecroComponent {
    }
}
declare global {
    interface HTMLNecroComponentElement extends Components.NecroComponent, HTMLStencilElement {
    }
    var HTMLNecroComponentElement: {
        prototype: HTMLNecroComponentElement;
        new (): HTMLNecroComponentElement;
    };
    interface HTMLElementTagNameMap {
        "necro-component": HTMLNecroComponentElement;
    }
}
declare namespace LocalJSX {
    interface NecroComponent {
    }
    interface IntrinsicElements {
        "necro-component": NecroComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "necro-component": LocalJSX.NecroComponent & JSXBase.HTMLAttributes<HTMLNecroComponentElement>;
        }
    }
}
